// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: msg.proto

package msg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	ClientInfo(ctx context.Context, in *ClientInfoRequest, opts ...grpc.CallOption) (*ClientInfoReply, error)
	Punch(ctx context.Context, in *PunchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PunchNotifier(ctx context.Context, in *PunchSubscribe, opts ...grpc.CallOption) (ControlService_PunchNotifierClient, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/msg.ControlService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ClientInfo(ctx context.Context, in *ClientInfoRequest, opts ...grpc.CallOption) (*ClientInfoReply, error) {
	out := new(ClientInfoReply)
	err := c.cc.Invoke(ctx, "/msg.ControlService/ClientInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) Punch(ctx context.Context, in *PunchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/msg.ControlService/Punch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) PunchNotifier(ctx context.Context, in *PunchSubscribe, opts ...grpc.CallOption) (ControlService_PunchNotifierClient, error) {
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[0], "/msg.ControlService/PunchNotifier", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlServicePunchNotifierClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControlService_PunchNotifierClient interface {
	Recv() (*PunchNotification, error)
	grpc.ClientStream
}

type controlServicePunchNotifierClient struct {
	grpc.ClientStream
}

func (x *controlServicePunchNotifierClient) Recv() (*PunchNotification, error) {
	m := new(PunchNotification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility
type ControlServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	ClientInfo(context.Context, *ClientInfoRequest) (*ClientInfoReply, error)
	Punch(context.Context, *PunchRequest) (*emptypb.Empty, error)
	PunchNotifier(*PunchSubscribe, ControlService_PunchNotifierServer) error
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedControlServiceServer struct {
}

func (UnimplementedControlServiceServer) Register(context.Context, *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedControlServiceServer) ClientInfo(context.Context, *ClientInfoRequest) (*ClientInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientInfo not implemented")
}
func (UnimplementedControlServiceServer) Punch(context.Context, *PunchRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Punch not implemented")
}
func (UnimplementedControlServiceServer) PunchNotifier(*PunchSubscribe, ControlService_PunchNotifierServer) error {
	return status.Errorf(codes.Unimplemented, "method PunchNotifier not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ControlService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ClientInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ClientInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ControlService/ClientInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ClientInfo(ctx, req.(*ClientInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_Punch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Punch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ControlService/Punch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Punch(ctx, req.(*PunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_PunchNotifier_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PunchSubscribe)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServiceServer).PunchNotifier(m, &controlServicePunchNotifierServer{stream})
}

type ControlService_PunchNotifierServer interface {
	Send(*PunchNotification) error
	grpc.ServerStream
}

type controlServicePunchNotifierServer struct {
	grpc.ServerStream
}

func (x *controlServicePunchNotifierServer) Send(m *PunchNotification) error {
	return x.ServerStream.SendMsg(m)
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "msg.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ControlService_Register_Handler,
		},
		{
			MethodName: "ClientInfo",
			Handler:    _ControlService_ClientInfo_Handler,
		},
		{
			MethodName: "Punch",
			Handler:    _ControlService_Punch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PunchNotifier",
			Handler:       _ControlService_PunchNotifier_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "msg.proto",
}
