services:
  controller:
    build:
      context: .
      dockerfile: controller/Dockerfile
      target: final
    ports:
      - 5050:5050/udp
      - 50000:50000/tcp
    volumes:
      #      - controller-data:/usr/share/overlay/data
      - type: bind
        source: .
        target: /home/overlay/data
  node:
    privileged: true
    build:
      context: .
      dockerfile: node/Dockerfile
      target: final
    environment:
      - 'CONTROLLER=10.170.241.193:50000'
      - 'HOME=/root'
#  frontend:
#    build:
#      context: controller/frontend
#      target: final
#    ports:
#      - 5173:8000


volumes:
  controller-data:
