# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.go'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Verify dependencies
      run: go mod verify
    
    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Make bin directory for artifacts
      run: mkdir ./bin

    - name: build controller
      run: go build -o ./bin/controller ./cmd/controller

    - name: build node
      run: go build -o ./bin/node ./cmd/node

    #- name: Test
     # run: go test

    - name: Run vet & lint
      run: |
        go vet ./...
        golint ./...

